export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  gmailSmtpUser: process.env.GMAIL_SMTP_USER ?? "",
  gmailAppPassword: process.env.GMAIL_APP_PASSWORD ?? "",
  bookingEmailTo: process.env.BOOKING_EMAIL_TO ?? "",
  adminPasswordFares: process.env.ADMIN_PASSWORD_FARES ?? "",
  adminPasswordYoussef: process.env.ADMIN_PASSWORD_YOUSSEF ?? "",
  adminSessionSecret: process.env.JWT_SECRET ?? "",
};
